/*
 * Swagger Kubechat
 *
 * Wrapper API of kubectl CLI command
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	_ "github.com/supernova106/kubechat/docs" // docs is generated by Swag CLI, you have to import it.
	sw "github.com/supernova106/kubechat/go"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// @title Swagger Kubechat API
// @version 0.1.0
// @description This is a API wraper of kubectl for chatbot
// @termsOfService http://swagger.io/terms/

// @contact.name Binh Nguyen
// @contact.url http://www.swagger.io/support
// @contact.email ntbinh106@gmail.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /v1
// @schemes http https
func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	log.Fatal(router.Run(":8080"))
}
